Added the new API action
Azure/GuestConfiguration pull request #303
Opened 2024-10-28 17:27 UTC by matheusbarbosasp

Updated the API version for non hybrid machines.

2024-10-28 18:28 UTC, kwirkykat commented
Why is this under Matheus? @ameyaiam3 Let me know if you're having permission issues?

2024-10-28 18:33 UTC, kwirkykat requested changes

2024-10-28 18:33 UTC, kwirkykat commented on source/templates/4-Action-Set-VMSS.json
> -                            "apiVersion": "2018-11-20",
I think the HybridCompute apiVersion can be updated as well. We should use the same apiVersion across all of them no?

2024-10-28 18:33 UTC, kwirkykat commented on source/templates/4-Action-Set.json
> -                            "apiVersion": "2018-11-20",
Same here. I think we should use the same updated apiVersion for HybridCompute as well

2024-10-30 23:48 UTC, kwirkykat approved these changes

2024-10-30 23:53 UTC, matheusbarbosasp commented
@microsoft-github-policy-service agree company="Microsoft"

2024-10-30 23:56 UTC, merged